### ISSUE TITLE
How do i open console window with the game so debug log is printed ?

### ISSUE THREAD

**Issue by whiletrue111** [vorlac/godot-roguelite#11]
Currently no way to print debug string to some output for example console window. 
It will be very useful to add console window that start with the game

**Comment by vorlac** [comment]
godot redirects all stdout/stderr/std::cout/std::cerr output through a complicated system so all output can be printed in the editor. I tried bypassing it a while ago but it was a lot more trouble than it was worth. you can use one of the print functions like [this](https://github.com/vorlac/godot-roguelite/blob/main/src/util/io.hpp#L127-L132) one to use one of the godot macros that should send anything you print with it to any terminal/IDE as well as the engine.

or you can use this to print to the in-game console I added instead:
https://github.com/vorlac/godot-roguelite/blob/main/src/singletons/console.hpp#L93-L96

**Comment by whiletrue111** [comment]
Thanks what about printing to file ? i saw that you already linking with log lib .
