### ISSUE TITLE
Web assembly compilation

### ISSUE THREAD

**Issue by PTSVU** [vorlac/godot-roguelite#19]
I am not very good at this, and I am having trouble compiling a .wasm file. I would like to ask for help with this issue.

**Comment by vorlac** [comment]
Sorry i've never messed with web assembly for gdextension, but it should be possible to create an export for it if you have the tooling installed. I think at the very least it should require a special compiler. Some of the folks in the godot discords should also be able to help you with this.

**Comment by PTSVU** [comment]
Understood. Thank you.
